"""This is variable for database"""

HOST = "ec2-46-137-91-216.eu-west-1.compute.amazonaws.com"
USER = "vobmeocqilozfo"
PASSWORD = "81886977eb54552e57161a1afcb236fb4a21ad3681abbad6921d72f6c41322c6"
DATABASE = "d9d5rats8b1tc1"


"""This is filter for tchat"""

GROS_MOTS = ["connard", "encule", "gros enculee", "pd",
             "con", "nique", "fils de pute", "salop",
             "salope", "merde", "chié",
             "trou du cul", "cul", "bite",
             "batard", "batar", "merde",
             "la con de ta race",
             "abruti",
             "aller chier dans sa caisse",
             "aller niquer sa mère",
             "aller se faire enculer",
             "aller se faire endauffer",
             "aller se faire foutre",
             "aller se faire mettre",
             "andouille",
             "appareilleuse",
             "astèque",
             "avorton",
             "bachi-bouzouk",
             "baleine",
             "bande d’abrutis",
             "bâtard",
             "baudet",
             "beauf",
             "bellicole",
             "bête",
             "bête à pleurer",
             "bête comme ses pieds",
             "bête comme un chou",
             "bête comme un cochon",
             "biatch",
             "bic",
             "bicot",
             "bicotte",
             "bite",
             "bitembois",
             "Bitembois",
             "bordille",
             "boucaque",
             "boudin",
             "bouffi",
             "bouffon",
             "bougnoul",
             "bougnoule",
             "Bougnoulie",
             "bougnoulisation",
             "bougnouliser",
             "bougre",
             "boukak",
             "boulet",
             "bounioul",
             "bounioule",
             "bourdille",
             "bourricot",
             "branleur",
             "bridé",
             "bridée",
             "brigand",
             "brise-burnes",
             ]
